<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.2360" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-02-13T15:27:16" tests="1" file="cypress/integration/difdjg.spec.js" time="1.2270" failures="1">
    <testcase name="An uncaught error was detected outside of a test" time="0.0000" classname="An uncaught error was detected outside of a test">
      <failure message="The following error originated from your test code, not from Cypress.

  &gt; Cannot call `cy.session()` outside a running test.

This usually happens when you accidentally write commands outside an `it(...)` test.

If that is the case, just move these commands inside an `it(...)` test.

Check your test file for errors.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

https://on.cypress.io/cannot-execute-commands-outside-test" type="CypressError"><![CDATA[CypressError: The following error originated from your test code, not from Cypress.

  > Cannot call `cy.session()` outside a running test.

This usually happens when you accidentally write commands outside an `it(...)` test.

If that is the case, just move these commands inside an `it(...)` test.

Check your test file for errors.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

https://on.cypress.io/cannot-execute-commands-outside-test
    at $Cy.ensureRunnable (http://localhost:59818/__cypress/runner/cypress_runner.js:163727:76)
    at $Cy.cy.<computed> [as session] (http://localhost:59818/__cypress/runner/cypress_runner.js:173122:10)
    at Object.create (http://localhost:59818/__cypress/runner/cypress_runner.js:121238:19)
    at context.describe.context.context (http://localhost:59818/__cypress/runner/cypress_runner.js:121014:27)
    at http://localhost:59818/__cypress/runner/cypress_runner.js:177738:21
    at http://localhost:59818/__cypress/runner/cypress_runner.js:180739:16
    at arrayEach (http://localhost:59818/__cypress/runner/cypress_runner.js:41318:11)
    at Function.forEach (http://localhost:59818/__cypress/runner/cypress_runner.js:50198:14)
    at evalScripts (http://localhost:59818/__cypress/runner/cypress_runner.js:180738:49)
    at http://localhost:59818/__cypress/runner/cypress_runner.js:180746:152
    at tryCatcher (http://localhost:59818/__cypress/runner/cypress_runner.js:13196:23)
    at Promise._settlePromiseFromHandler (http://localhost:59818/__cypress/runner/cypress_runner.js:11131:31)
    at Promise._settlePromise (http://localhost:59818/__cypress/runner/cypress_runner.js:11188:18)
    at Promise._settlePromise0 (http://localhost:59818/__cypress/runner/cypress_runner.js:11233:10)
    at Promise._settlePromises (http://localhost:59818/__cypress/runner/cypress_runner.js:11313:18)
    at Promise._fulfill (http://localhost:59818/__cypress/runner/cypress_runner.js:11257:18)]]></failure>
    </testcase>
  </testsuite>
</testsuites>